### ISSUE TITLE
Warn for linker attributes which are no longer needed

### ISSUE THREAD

**Issue by roji** [dotnet/linker#2527] opened 2022-01-20 12:32 UTC
As a code base evolves, various linker annotations may no longer be needed. For example, a DynamicallyAccessedMembers annotation may no longer be needed after a method implementation changed, but it may linger there, causing code to be needlessly preserved when it could be trimmed.

The linker (or analyzer) could warn about DynamicallyAccessedMembers which aren't actually needed. The same could also be done for UnconditionalSuppressMessage, when a diagnostic is being supressed that doesn't actually get generated in the covered code (probably out of scope as a linker-only change).

**Comment by vitek-karas** [comment] 2022-01-20 16:09
Duplicate of https://github.com/dotnet/linker/issues/1971.

**Closed by vitek-karas** 2022-01-20 16:09 UTC
Labels: area-Analyzers
