### ISSUE TITLE
Mono.Linker.MarkException in release mode

### ISSUE THREAD

**Issue by jitendrajadav** [dotnet/linker#1662] opened 2020-12-02 06:03 UTC
Severity	Code	Description	Project	File	Line	Suppression State
Error		Mono.Linker.MarkException: Error processing method: 'System.String Microsoft.Net.Http.Headers.DateTimeFormatter::ToRfc1123String(System.DateTimeOffset,System.Boolean)' in assembly: 'Microsoft.Net.Http.Headers.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve Microsoft.Extensions.Primitives.InplaceStringBuilder
   at Mono.Linker.Steps.MarkStep.HandleUnresolvedType(TypeReference reference)
   at Mono.Linker.Steps.MarkStep.MarkType(TypeReference reference)
   at MonoDroid.Tuner.MonoDroidMarkStep.MarkType(TypeReference reference)
   at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
   at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   --- End of inner exception stack trace ---
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
   at Mono.Linker.Steps.MarkStep.Process()
   at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
   at MonoDroid.Tuner.MonoDroidMarkStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at MonoDroid.Tuner.Linker.Process(LinkerOptions options, ILogger logger, LinkContext& context)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   at Xamarin.Android.Tasks.LinkAssemblies.RunTask()
   at Xamarin.Android.Tasks.AndroidTask.Execute()	KegID.Android

**Comment by marek-safar** [comment] 2020-12-03 11:33
Could you please share details how to reproduce the issue?

**Comment by jitendrajadav** [comment] 2020-12-04 10:01
I have added lots of third party nuget packages and try to run application in release mode so while building application I am getting error I have created sample repository please have a look

[Sample Project](https://github.com/jitendrajadav/AndroidLinkerError.git)

**Comment by marek-safar** [comment] 2020-12-07 16:36
@radekdoulik this looks like issue how pre-netcore XA builds a list of referenced assemblies passed to linker.

**Comment by radekdoulik** [comment] 2020-12-08 12:15
This usually means that one of the assemblies coming from the nugets is missing a reference and linker is first tool to run into that.

The sample project doesn't build for me, but I think the project mixes pre-netcore and net5 packages. Try to use lower version than 5.x of packages like `Microsoft.Extensions.Primitives`.

@dellis1972 @jonathanpeppers, this might be interesting for you. Do we already issue a warning about net5 package references, when targetting pre-net5/6 XA?

**Comment by jitendrajadav** [comment] 2020-12-08 12:27
[kegid-x.zip](https://github.com/mono/linker/files/5659224/kegid-x.zip)
@radekdoulik thank you for for suggestion, meanwhile I am checking and downgrading .net5 please check this uploaded sample working which is I am following.

**Comment by jitendrajadav** [comment] 2020-12-11 09:16
I have converted back to all stable but still same error no luck any idea or work around to solved this problem?

**Comment by GZidar** [comment] 2021-03-12 04:25
I am having this exact same problem. I should note that the app is referencing libraries built with .net core 3.1 which are targeting netstandard 2.0

**Comment by arivera12** [comment] 2021-03-17 21:16
I just hit this error any news on this?

**Comment by arivera12** [comment] 2021-03-18 03:48
Ok I fix my android project I rolled back from a base library nuget package reference which was being reference by the android project from:

```
<PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="5.0.0" />
<PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="5.0.0" />
<PackageReference Include="Microsoft.Extensions.Options" Version="5.0.0" />
```
To:
```
<PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="3.1.13" />
<PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="3.1.13" />
<PackageReference Include="Microsoft.Extensions.Options" Version="3.1.13" />
```
Hope this helps someone to workaround temporary when this gets fixed.

**Comment by arivera12** [comment] 2021-03-19 12:56
It's seems if there any package mixed with versions 3.* and 5.* this error gets raised up. When this gonna get fixed? It's quite annoying since if a dependency package gets update with something pointing version 5.* then this gets thrown...

**Comment by BoobalanK** [comment] 2021-06-09 11:21
Hi everyone,

I still face this linker mark exception

`Severity	Code	Description	Project	File	Line	Suppression State
Error		Mono.Linker.MarkException: Error processing method: 'System.String Microsoft.Net.Http.Headers.DateTimeFormatter::ToRfc1123String(System.DateTimeOffset,System.Boolean)' in assembly: 'Microsoft.Net.Http.Headers.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve Microsoft.Extensions.Primitives.InplaceStringBuilder
   at Mono.Linker.Steps.MarkStep.HandleUnresolvedType(TypeReference reference)
   at Mono.Linker.Steps.MarkStep.MarkType(TypeReference reference)
   at MonoDroid.Tuner.MonoDroidMarkStep.MarkType(TypeReference reference)
   at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
   at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   --- End of inner exception stack trace ---
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
   at Mono.Linker.Steps.MarkStep.Process()
   at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
   at MonoDroid.Tuner.MonoDroidMarkStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at MonoDroid.Tuner.Linker.Process(LinkerOptions options, ILogger logger, LinkContext& context)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   at Xamarin.Android.Tasks.LinkAssemblies.RunTask()
   at Xamarin.Android.Tasks.AndroidTask.Execute()	BackgroundServiceSample.Android			
`

The csproj of the project is below

`<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <UserSecretsId>dotnet-SampleApp.BackgroundService-B34FBB98-640E-42AE-96D2-83251EE87CE4</UserSecretsId>
    <OutputType>Exe</OutputType>
    <LangVersion>9.0</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.2.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="3.1.13" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="3.1.13" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="3.1.13" />
    <PackageReference Include="Serilog" Version="2.10.0" />
    <PackageReference Include="Serilog.Extensions.Logging" Version="3.0.1" />
    <PackageReference Include="System.Threading.Channels" Version="5.0.0" />
  </ItemGroup>
</Project>
`

Kindly assist please

**Comment by arivera12** [comment] 2021-06-09 14:24
@BoobalanK try downgrading `System.Threading.Channels` to a 3.* version

**Comment by RogerFraserZa** [comment] 2021-06-30 11:33
Hi I faced the same issue today . Tried to change the Nuget packages and versions but it did not help .  Stumbled onto this workaround [https://docs.microsoft.com/en-us/answers/questions/299016/xamarin-error-xalnk7000-monolinkermarkexception.html](url) 
I have now Set VS Link Assemblies to "None" in the Android project Android options as suggested and my builds are working now .Seems the linker is stripping out some required functions .

**Comment by ivanrlg** [comment] 2022-01-04 01:26
Hello any update with this? I am getting the same error.

**Comment by BoobalanK** [comment] 2022-01-11 17:42
Thanks for the suggestion @arivera12.

I have solved it by removing the aspnetcore nuget packages.
![image](https://user-images.githubusercontent.com/22682404/148993874-fa36ba74-04e0-4667-8cc5-30b05447acd5.png)

**Comment by vitek-karas** [comment] 2022-09-16 15:18
In general version mismatches are hard to work with - most cases here lead to situations where library A references a member from B which doesn't exist in the version resolved by the project. And linker is the first to run into this problem - if the code gets called at runtime, it would also fail.

The new linker (.NET 6+) should be much more resilient to these situations, I tried simple cases like missing field or method references and linker will process these without trouble (the code would still fail at runtime).

**Closed by vitek-karas** 2022-09-16 15:18 UTC
Labels: needs more info
