### ISSUE TITLE
Analyzer 'ILLink.RoslynAnalyzer.RequiresUnreferencedCodeAnalyzer' threw an exception of type 'System.NullReferenceException'

### ISSUE THREAD

**Issue by meziantou** [dotnet/linker#2683] opened 2022-03-13 01:59 UTC
I get an NRE in RequiresUnreferencedCodeAnalyzer when using an assembly attribute.

Repro steps:

````xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsTrimmable>true</IsTrimmable>
  </PropertyGroup>
</Project>
````

Add a single cs file with the following content:

````c#
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0016:Use 'throw' expression", Justification = "<Pending>", Scope = "member", Target = "~M:Dummy.SetCurrentThreadCulture(System.Globalization.CultureInfo)")]
````

The Roslyn Analyzer throws a NRE:

````
Warning	AD0001	Analyzer 'ILLink.RoslynAnalyzer.RequiresUnreferencedCodeAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.
Exception occurred with following context:
Compilation: ClassLibrary1
IOperation: PropertyReference
SyntaxTree: C:\Users\mezia\source\repos\ClassLibrary1\ClassLibrary1\GlobalSuppressions.cs
SyntaxNode: Justification [IdentifierNameSyntax]@[102..115) (0,102)-(0,115)

System.NullReferenceException: Object reference not set to an instance of an object.
   at ILLink.RoslynAnalyzer.ISymbolExtensions.HasAttribute(ISymbol symbol, String attributeName)
   at ILLink.RoslynAnalyzer.RequiresISymbolExtensions.IsInRequiresScope(ISymbol member, String requiresAttribute, Boolean checkAssociatedSymbol)
   at ILLink.RoslynAnalyzer.RequiresAnalyzerBase.<Initialize>g__CheckCalledMember|19_14(OperationAnalysisContext operationContext, ISymbol member, ImmutableArray`1 incompatibleMembers)
   at ILLink.RoslynAnalyzer.RequiresAnalyzerBase.<>c__DisplayClass19_0.<Initialize>b__9(OperationAnalysisContext operationContext)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c.<ExecuteOperationAction>b__63_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
````

`dotnet --info`

````
.NET SDK (reflecting any global.json):
 Version:   7.0.100-preview.1.22110.4
 Commit:    129d2465c8

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.100-preview.1.22110.4\

Host (useful for support):
  Version: 7.0.0-preview.1.22076.8
  Commit:  405337939c

.NET SDKs installed:
  3.1.417 [C:\Program Files\dotnet\sdk]
  5.0.406 [C:\Program Files\dotnet\sdk]
  6.0.102 [C:\Program Files\dotnet\sdk]
  6.0.200 [C:\Program Files\dotnet\sdk]
  7.0.100-preview.1.22110.4 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0-preview.1.22109.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0-preview.1.22076.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.0-preview.1.22077.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
````

**Comment by tlakollo** [comment] 2022-03-13 22:41
This problem seems to be fixed in main by https://github.com/dotnet/linker/pull/2534. Can you try using the latest installer from https://github.com/dotnet/installer

**Comment by meziantou** [comment] 2022-03-13 22:46
You are right. It seems to be ok with the version `7.0.0-preview.3.22151.6`!

**Comment by tannergooding** [comment] 2022-03-15 16:24
@tlakollo, this is fixed by main but represents a regression for the .NET 6 SDK. Can we look at backporting the fix so that .NET 6 continues to work as it did when it shipped?

**Comment by tlakollo** [comment] 2022-03-15 16:27
@tannergooding I think that's fixed by https://github.com/dotnet/linker/pull/2530

**Comment by tlakollo** [comment] 2022-03-15 16:36
That might be a different issue then. @eerhardt just filled https://github.com/dotnet/linker/issues/2686 which has the same signature

**Comment by tannergooding** [comment] 2022-03-15 16:38
Thanks! That does look to be the case.

**Closed by tannergooding** 2022-03-15 16:38 UTC

**Comment by JimBobSquarePants** [comment] 2025-01-07 10:11
Has a regression been introduced again? I'm suddenly seeing the same error in a recent PR to one of my libraries.

.NET 6.0.428

https://github.com/SixLabors/Fonts/actions/runs/12649165049/job/35245405122?pr=438#step:12:69

![Image](https://github.com/user-attachments/assets/12bbf58f-ca52-4135-8a90-0056252cc642)

**Comment by akoeplinger** [comment] 2025-01-07 14:26
@JimBobSquarePants that failure is from a different analyzer, would you mind opening a new issue in dotnet/runtime (as the readme mentions the linker got moved there)? Preferably with a binlog since that will show the stack trace.
