### ISSUE TITLE
RequiresAssemblyFilesAnalyzer throws InvalidCastException

### ISSUE THREAD

**Issue by nagya** [dotnet/linker#2651] opened 2022-02-24 20:20 UTC
From https://github.com/dotnet/roslyn/issues/59749

**Version Used**: 6.0.200, bug is new in this version, i.e. was not present in 6.0.1

**Steps to Reproduce**:

1. [Test1.zip](https://github.com/dotnet/roslyn/files/8135375/Test1.zip)
2. `dotnet build`

**Expected Behavior**:

No compile time exception and no warning.

**Actual Behavior**:

```
CSC : warning AD0001: Analyzer 'ILLink.RoslynAnalyzer.RequiresAssemblyFilesAnalyzer' threw an exception of type 'System.InvalidCastException' with message 'Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.Symbols.PublicModel.TypeParameterSymbol' to type 'Microsoft.CodeAnalysis.INamedTypeSymbol'.'. 
```

**Repro project details**:

`PublishSingleFile=true` must be set in the project file, and both type constraints are needed in the source file.

## Test1.csproj
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <PublishSingleFile>true</PublishSingleFile>
  </PropertyGroup>
</Project>
```

## Class1.cs
```
namespace Test1;

public abstract class Class1<T> where T : Class1<T>, new() { }
```

**Comment by sbomer** [comment] 2022-02-24 21:01
Duplicate of https://github.com/dotnet/linker/issues/2642

**Closed by sbomer** 2022-02-24 21:01 UTC

**Comment by nagya** [comment] 2022-02-24 22:00
> Duplicate of #2642

Which public release will include the fix? Can you please provide a workaround in the meanwhile?

**Comment by sbomer** [comment] 2022-02-24 23:10
I think it is set to ship with the next patch release of the 6.0.2xx SDK, @agocke can you confirm? As a workaround, you have a few options:
- Disable the analyzer temporarily `<EnableSingleFileAnalyzer>false</EnableSingleFileAnalyzer>`
- Update to a recent .NET 7 preview build from https://github.com/dotnet/installer (I don't think the preview1 release has the fix).
- If you are interested I can provide instructions on using a locally-built analyzer with the fix, with the 6.0.200 SDK.

**Comment by nagya** [comment] 2022-02-24 23:55
Great, thank you. Disabling temporarily with a property is a good workaround in my scenario.

**Comment by sbomer** [comment] 2022-03-02 18:03
I just realized that setting `<NoWarn>$(NoWarn);AD0001</NoWarn>` may be a better workaround since this appears to continue producing warnings from the analyzer for other methods (whereas by disabling it entirely might cause you to miss real issues).

**Comment by nagya** [comment] 2022-03-11 21:14
Still repros in 6.0.201.
