### ISSUE TITLE
Fatal error in IL Linker - System.NullReferenceException

### ISSUE THREAD

**Issue by jwosty** [dotnet/linker#2281] opened 2021-09-18 22:34 UTC
I have an F# app that I'm attempting to migrate from Xamarin.Mac to .Net 6 RC 1. Windows host works fine.

Building via ``dotnet build src/App.MacOS/App.MacOS.fsproj`` crashes with:

```
ILLINK : warning MM0079: The recommended Xcode version for Microsoft.macOS 12.0.100 is Xcode 13.0 or later. The current Xcode version (found in /Applications/Xcode.app/Contents/Developer) is 12.4. [/Users/jwosty/Code/FSharp/App/src/App.MacOS/App.MacOS.fsproj]
  		
ILLink : error IL1012: IL Linker has encountered an unexpected error. Please report the issue at https://github.com/mono/linker/issues [/Users/jwosty/Code/FSharp/App/src/App.MacOS/App.MacOS.fsproj]
  Fatal error in IL Linker
  Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
     at Mono.Cecil.SignatureReader.GetGenericParameter(GenericParameterType type, UInt32 var)
     at Mono.Cecil.SignatureReader.ReadTypeSignature(ElementType etype)
     at Mono.Cecil.SignatureReader.ReadTypeSignature()
     at Mono.Cecil.SignatureReader.ReadGenericInstanceSignature(IGenericParameterProvider provider, IGenericInstance instance, UInt32 arity)
     at Mono.Cecil.SignatureReader.ReadTypeSignature(ElementType etype)
     at Mono.Cecil.SignatureReader.ReadTypeSignature()
     at Mono.Cecil.MetadataReader.ReadProperty(UInt32 property_rid, Collection`1 properties)
     at Mono.Cecil.MetadataReader.ReadProperties(TypeDefinition type)
     at Mono.Cecil.TypeDefinition.<>c.<get_Properties>b__55_0(TypeDefinition type, MetadataReader reader)
     at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TRet& variable, TItem item, Func`3 read)
     at Mono.Cecil.TypeDefinition.get_Properties()
     at Mono.Linker.Steps.DiscoverSerializationHandler.ProcessType(TypeDefinition type)
     at Mono.Linker.Steps.MarkStep.MarkType(TypeReference reference, DependencyInfo reason, Nullable`1 origin)
     at Mono.Linker.Steps.MarkStep.MarkInterfaceImplementation(InterfaceImplementation iface, Nullable`1 origin, Nullable`1 reason)
     at Mono.Linker.Steps.MarkStep.MarkEntireType(TypeDefinition type, DependencyInfo& reason)
     at Mono.Linker.Steps.MarkStep.MarkEntireAssembly(AssemblyDefinition assembly)
     at Mono.Linker.Steps.MarkStep.MarkAssembly(AssemblyDefinition assembly, DependencyInfo reason)
     at Mono.Linker.Steps.MarkStep.ProcessMarkedPending()
     at Mono.Linker.Steps.MarkStep.Initialize()
     at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
     at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
     at Mono.Linker.Pipeline.Process(LinkContext context)
     at Mono.Linker.Driver.Run(ILogger customLogger)
     at Mono.Linker.Driver.Main(String[] args)
  Optimizing assemblies for size, which may change the behavior of the app. Be sure to test after publishing. See: https://aka.ms/dotnet-illink
/usr/local/share/dotnet/sdk/6.0.100-rc.1.21458.32/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.ILLink.targets(108,5): error NETSDK1144: Optimizing assemblies for size failed. Optimization can be disabled by setting the PublishTrimmed property to false. [/Users/jwosty/Code/FSharp/App/src/App.MacOS/App.MacOS.fsproj]

Build FAILED.

ILLINK : warning MM0079: The recommended Xcode version for Microsoft.macOS 12.0.100 is Xcode 13.0 or later. The current Xcode version (found in /Applications/Xcode.app/Contents/Developer) is 12.4. [/Users/jwosty/Code/FSharp/App/src/App.MacOS/App.MacOS.fsproj]
ILLink : error IL1012: IL Linker has encountered an unexpected error. Please report the issue at https://github.com/mono/linker/issues [/Users/jwosty/Code/FSharp/App/src/App.MacOS/App.MacOS.fsproj]
/usr/local/share/dotnet/sdk/6.0.100-rc.1.21458.32/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.ILLink.targets(108,5): error NETSDK1144: Optimizing assemblies for size failed. Optimization can be disabled by setting the PublishTrimmed property to false. [/Users/jwosty/Code/FSharp/App/src/App.MacOS/App.MacOS.fsproj]
    1 Warning(s)
    2 Error(s)

```

The only repro I have is my private repository. If more info is needed, I can attempt to create a repro which I am comfortable sharing publicly. Alternatively, I'm happy to share the app projects privately with an MS employee if that would help.

I have a different, working F# mac app using .NET 6 here: https://github.com/fsprojects/Interstellar/pull/22 , so it seems to be a problem with this particular codebase.

I don't have a workaround, as adding ``<PublishTrimmed>true</PublishTrimmed>`` lets the build succeed, but generates an invalid/unrunnable app bundle (missing the entry point executable).
System info:
```
=== Visual Studio Community 2019 for Mac ===

Version 8.10.9 (build 3)
Installation UUID: 290bbaa8-262e-4c8c-b800-82712d5961b9
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000140

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.140 (2020-02/51d876a041e) (64-bit)
	Package version: 612000140

=== Roslyn (Language Service) ===

3.10.0-4.21269.26+029847714208ebe49668667c60ea5b0a294e0fcb

=== NuGet ===

Version: 5.9.0.7134

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/6.0.100-rc.1.21458.32/Sdks
SDK Versions:
	6.0.100-rc.1.21458.32
	6.0.100-preview.7.21379.14
	5.0.401
	5.0.400
	3.1.413
	3.1.412
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	6.0.0-rc.1.21451.13
	6.0.0-preview.7.21377.19
	5.0.10
	5.0.9
	3.1.19
	3.1.18

=== .NET Core 3.1 SDK ===

SDK: 3.1.413

=== Xamarin.Profiler ===

Version: 1.6.12.29
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Xamarin.Android ===

Version: 11.3.0.4 (Visual Studio Community)
Commit: xamarin-android/d16-10/ae14caf
Android SDK: /Users/jwostenberg/Library/Android/sdk
	Supported Android versions:
		6.0 (API level 23)
		7.0 (API level 24)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.3
SDK Build Tools Version: 30.0.2

Build Information: 
Mono: b4a3858
Java.Interop: xamarin/java.interop/d16-10@f39db25
ProGuard: Guardsquare/proguard/v7.0.1@912d149
SQLite: xamarin/sqlite/3.35.4@85460d3
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-10@c5732a0

=== Microsoft OpenJDK for Mobile ===

Java SDK: /Users/jwostenberg/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.10.0.13
Hash: 1b81df5
Branch: remotes/origin/d16-10
Build date: 2021-08-12 20:43:52 UTC

=== Android Device Manager ===

Version: 16.10.0.15
Hash: 89dcc0b
Branch: remotes/origin/d16-10
Build date: 2021-08-12 20:44:10 UTC

=== Apple Developer Tools ===

Xcode 12.4 (17801)
Build 12D4e

=== Xamarin.Mac ===

Version: 7.14.0.24 (Visual Studio Community)
Hash: c4b89cddb
Branch: d16-10
Build date: 2021-06-15 22:03:00-0400

=== Xamarin.iOS ===

Version: 14.20.0.24 (Visual Studio Community)
Hash: c4b89cddb
Branch: d16-10
Build date: 2021-06-15 22:03:01-0400

=== Xamarin Designer ===

Version: 16.10.0.119
Hash: 36a2d986f
Branch: remotes/origin/d16-10
Build date: 2021-06-02 19:41:34 UTC

=== Build Information ===

Release ID: 810090003
Git revision: 156eb53c9c668cb7ff4311ae3d1dab894549848b
Build date: 2021-09-08 07:26:54-04
Build branch: release-8.10

=== Operating System ===

Mac OS X 10.15.7
Darwin 19.6.0 Darwin Kernel Version 19.6.0
    Tue Jun 22 19:49:55 PDT 2021
    root:xnu-6153.141.35~1/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

LiveXAML 1.3.51
Paket 0.6
Open With 0.2
XAML Styler 2.0.1
MvvmCross Template pack 2.1.0
```

**Comment by marek-safar** [comment] 2021-09-20 09:35
It'd be very helpful if you could attach the assembly which is causing the crash because there is no obvious reason why `GetGenericParameter` context should be null.

**Comment by vitek-karas** [comment] 2021-09-24 21:56
Thanks a lot @jwosty for the offline repro.

The problem is with a property which looks like this:
```C#
FSharpFunc<SomeType, !!0> name { get; set; }
```

Honestly I don't know what the `!!0` refers to. In a method parameter `!!0` means "The generic parameter of the method with index 0". But what does that mean in the context of a property?

I honestly don't know if IL allows to define a generic property. The getter on this property is a generic method, which is I guess OK, but for example it's impossible to declare this in C# (C# doesn't allow generic properties in syntax as in `public string Foo<T> {get; set; }`)

Anyway, this breaks Cecil when parsing the signature for the property.
This also breaks `System.Reflection.MetadataLoadContext` which can't load it either (it fails on it as well).

We'll have to wait for @MichalStrehovsky  to answer the question if this is even valid IL.

**Comment by jwosty** [comment] 2021-09-25 02:19
Interesting, I couldn't get F# to generate a generic property such as we're seeing, so I'm not sure how this is getting generated either. Tried a few times:

```fsharp
type SomeType() =
    // compiler error FS0671: A property cannot have explicit type parameters. Consider using a method instead.
    member this.SomeProperty<'a> = Unchecked.defaultof<'a>
```

```fsharp
module SomeModule =
    // compiles, but emits a method, not a property or field
    let value<'a> = Unchecked.defaultof<'a>
```

Is there some kind of tracing I can turn on that shows me what specific property this is inside the assembly in question? I wonder if it is a bug in the F# compiler.

**Comment by MichalStrehovsky** [comment] 2021-09-26 03:53
> We'll have to wait for @MichalStrehovsky to answer the question if this is even valid IL.

I don't see generic properties being spelled out as invalid in the file format spec, but I would consider it implied because a generic parameter can only be owned by a method or a type. It's unclear which parameter the !!0 refers to (getter's? setter's? the other method's?).

@vitek-karas how does the associated getter/setter look like? Is it generic as well?

@jwosty are you using any kind of IL rewriter (Fody? etc.)

**Comment by jwosty** [comment] 2021-09-26 22:14
> @jwosty are you using any kind of IL rewriter (Fody? etc.)

Nope, just the vanilla F# (and C#) compilers.

**Comment by Continuitis** [comment] 2021-09-27 17:10
Hello,
I have the same issue on my C# project (https://github.com/Azure/static-web-apps/issues/590)... Any news on a fix?

**Comment by jwosty** [comment] 2021-09-27 17:20
> 
> 
> Hello,
> I have the same issue on my C# project ([Azure/static-web-apps#590](https://github.com/Azure/static-web-apps/issues/590))... Any news on a fix?

Looking at your stacktrace, the root cause is something different. It seems to be tripping over mine because apparently my assembly is ending up with generic property somewhere inside it, while yours seems to have to do with custom attributes.

I do not have a workaround for this class of problems right now.

**Comment by marek-safar** [comment] 2021-09-27 17:45
@Continuitis your issues is tracked as #2274

**Comment by vitek-karas** [comment] 2021-09-27 18:20
I don't know FSharp this well, but based on the names I think the source code for the affected code is here: https://github.com/fable-compiler/fable-browser/blob/36faa2e689fb8ea34ce91f73d08a9dc5630b3316/src/Dom/Browser.Dom.fs#L1056

```fsharp
abstract onpointercancel: (PointerEvent -> 'Out) with get, set
```

I honestly have no idea what `'Out` means.

**Comment by dsyme** [comment] 2021-09-27 21:57
There's no such thing as generic properties so this kind of looks like a bug in the F# compiler.

**Comment by jwosty** [comment] 2021-09-27 22:29
> 
> I honestly have no idea what `'Out` means.

It's nonsensical. It should be replaced with Object.

**Comment by MichalStrehovsky** [comment] 2021-09-28 02:05
Thanks @dsyme! I haven't seen an issue for it so I filed it as https://github.com/dotnet/fsharp/issues/12198 so that it won't get lost.

While we could certainly do work to let the broken metadata through, it seems like fixing the bug in Fable is a better avenue.

I'm leaning towards won't fixing this.

**Comment by jwosty** [comment] 2021-09-28 04:01
Perhaps at least a slightly improved error message could help here? At least so the linker still blows up, but with a helpful message in the case of this kind of weird IL. I.e. instead of ``NullReferenceException`` we see something like "Invalid generic parameter encountered" or something.

**Comment by agocke** [comment] 2021-09-30 20:32
I don't think there's a lot to do in the linker here. Up to Cecil if they want to do more robust error checking around this case, although I question whether or not this is worth it, if the only way to encounter the problem is from broken compiler IL.

**Closed by agocke** 2021-09-30 20:32 UTC
