### ISSUE TITLE
NullReferenceException from IL Linker when using Blazor WASM AoT

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/linker#2290] opened 2021-09-23 01:41 UTC
- Clone https://github.com/dsplaisted/MSBuildStructuredLog
- Check out commit [2970055](https://github.com/dsplaisted/MSBuildStructuredLog/commit/2970055062010ada4d440b6bdc6c8c65b6f06d56)
- `cd src\StructuredLogViewer.Web`
- `dotnet publish -p:Configuration=Release /p:RunAOTCompilation=true`

**Expected:** Successful publish

**Actual:** Null reference in IL Linker (and the build also seems to hang, rather then ending with an error):

```
ILLink : error IL1012: IL Linker has encountered an unexpected error. Please report the issue at https://github.com/mono/linker/issues [C:\git\MSBuildStructuredLog\src\StructuredLogViewer.Web\StructuredLogViewer.Web.csproj]
  Fatal error in IL Linker
  Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
     at Mono.Linker.CustomAttributeSource.HasAny(ICustomAttributeProvider provider)
     at Mono.Linker.AnnotationStore.GetLinkerAttributes[T](IMemberDefinition member)
     at Mono.Linker.AnnotationStore.TryGetLinkerAttribute[T](IMemberDefinition member, T& attribute)
     at Mono.Linker.Steps.MarkStep.MarkType(TypeReference reference, DependencyInfo reason, Nullable`1 origin)
     at Mono.Linker.Steps.MarkStep.MarkField(FieldDefinition field, DependencyInfo& reason)
     at Mono.Linker.Steps.MarkStep.MarkEntireType(TypeDefinition type, DependencyInfo& reason)
     at Mono.Linker.Steps.MarkStep.MarkEntireType(TypeDefinition type, DependencyInfo& reason)
     at Mono.Linker.Steps.MarkStep.MarkEntireAssembly(AssemblyDefinition assembly)
     at Mono.Linker.Steps.MarkStep.MarkAssembly(AssemblyDefinition assembly, DependencyInfo reason)
     at Mono.Linker.Steps.MarkStep.ProcessMarkedPending()
     at Mono.Linker.Steps.MarkStep.Initialize()
     at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
     at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
     at Mono.Linker.Pipeline.Process(LinkContext context)
     at Mono.Linker.Driver.Run(ILogger customLogger)
     at Mono.Linker.Driver.Main(String[] args)
```

**.NET SDK version:** 6.0.100-rc.1.21458.32

**Workload versions:**

> ==workloadRollbackDefinitionJsonOutputStart==
{"microsoft.net.sdk.android":"31.0.100-rc.1.12","microsoft.net.sdk.ios":"15.0.100-rc.1.1534","microsoft.net.sdk.maccatalyst":"15.0.100-rc.1.1534","microsoft.net.sdk.macos":"12.0.100-rc.1.1534","microsoft.net.sdk.maui":"6.0.100-rc.1.1608","microsoft.net.sdk.tvos":"15.0.100-rc.1.1534","microsoft.net.workload.emscripten":"6.0.0-rc.1.21430.3","microsoft.net.workload.mono.toolchain":"6.0.0-rc.1.21451.13"}
==workloadRollbackDefinitionJsonOutputEnd==

I'm able to successfully publish the blazorwasm template with AoT, so it seems like something in the Structured Log Viewer code is causing it to fail.

**Comment by marek-safar** [comment] 2021-09-23 10:26
Duplicate of #2274

**Closed by marek-safar** 2021-09-23 10:26 UTC
Labels: duplicate
