### ISSUE TITLE
6.0.200 Regression: COMAnalyzer chokes on PInvoke with pointer argument

### ISSUE THREAD

**Issue by dorssel** [dotnet/linker#2622] opened 2022-02-16 17:11 UTC
My project uses a lot of CsWin32 automatically generated PInvokes.
Since updating from 6.0.102 to 6.0.200 I get a lot of 

```
CSC : warning AD0001: Analyzer 'ILLink.RoslynAnalyzer.COMAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.
```

I distilled to the following minimal program that reproduces the warning:

```csharp
using System.Runtime.InteropServices;

static class Program
{
    // Since 6.0.200:
    // CSC : warning AD0001: Analyzer 'ILLink.RoslynAnalyzer.COMAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.
    //
    // Only when the trim analyzer is enabled (e.g. with <PublishTrimmed>true</PublishTrimmed>)
    [DllImport("Unimportant")]
    static extern unsafe void WhateverName(void* pointerArg);

    static void Main()
    {
        unsafe
        {
            // Make sure the problematic function is used and not optimized away.
            // NOTE: This is not the NullReferenceException of the warning, that is thrown by the analyzer itself.
            WhateverName(null);
        }
    }
}
```

**Comment by tlakollo** [comment] 2022-02-19 05:54
Closing via https://github.com/dotnet/linker/pull/2623

**Comment by marek-safar** [comment] 2022-02-19 09:23
Reopening as the issue was fixed in master and this is a regression in 6.0.

**Comment by sbomer** [comment] 2022-04-15 18:34
Closing since the fix for this was backported in https://github.com/dotnet/linker/pull/2635

**Closed by sbomer** 2022-04-15 18:34 UTC

**Comment by Naine** [comment] 2022-07-08 14:45
I am getting this issue in SDK 6.0.301, which supposedly has the fix. In my case the PInvoke is using function pointers.

I had a look at the PR. The fix looks incomplete: the check for `IPointerTypeSymbol` should also check for `IFunctionPointerTypeSymbol`.

**Comment by jtschuster** [comment] 2022-07-13 18:48
@sbomer Looks like this was fixed with the change that adds a null check for `symbol.ContainingNamespace.Name`. Should we backport those changes to release/6.0.x?

cc @agocke
