### ISSUE TITLE
NRE in Linker on `dotnet/runtime` perf pipeline

### ISSUE THREAD

**Issue by radical** [dotnet/linker#2895] opened 2022-07-15 20:44 UTC
Build `20220715.1`, `Performance Linux x64 release wasm aot micro perftiger v8 False net7.0`, for `dotnet-runtime-perf` internal pipeline.

```
[2022/07/15 02:25:15][INFO] ILLink : error IL1012: IL Trimmer has encountered an unexpected error. Please report the issue at https://github.com/dotnet/linker/issues [/home/helixbot/work/AFA60946/w/C27A0A71/e/performance/artifacts/bin/for-running/MicroBenchmarks/f6eeab76-cb0e-4c5b-a534-b42263d1519d/BenchmarkDotNet.Autogenerated.csproj]
[2022/07/15 02:25:15][INFO]   Fatal error in IL Linker
[2022/07/15 02:25:15][INFO]   Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
[2022/07/15 02:25:15][INFO]      at Mono.Linker.TypeReferenceWalker.WalkTypeScope(MethodBody body)
[2022/07/15 02:25:15][INFO]      at Mono.Linker.TypeReferenceWalker.WalkScopes(TypeDefinition typeDefinition)
[2022/07/15 02:25:15][INFO]      at Mono.Linker.TypeReferenceWalker.WalkScopes(TypeDefinition typeDefinition)
[2022/07/15 02:25:15][INFO]      at Mono.Linker.TypeReferenceWalker.Process()
[2022/07/15 02:25:15][INFO]      at Mono.Linker.Steps.SweepStep.AssemblyReferencesCorrector.SweepAssemblyReferences(AssemblyDefinition assembly)
[2022/07/15 02:25:15][INFO]      at Mono.Linker.Steps.SweepStep.Process()
[2022/07/15 02:25:15][INFO]      at Mono.Linker.Steps.BaseStep.Process(LinkContext context)
[2022/07/15 02:25:15][INFO]      at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
[2022/07/15 02:25:15][INFO]      at Mono.Linker.Pipeline.Process(LinkContext context)
[2022/07/15 02:25:15][INFO]      at Mono.Linker.Driver.Run(ILogger customLogger)
[2022/07/15 02:25:15][INFO]      at Mono.Linker.Driver.Main(String[] args)
```

**Comment by marek-safar** [comment] 2022-07-18 16:19
Duplicate of #2896

**Closed** 2022-07-18 16:19 UTC
Labels: duplicate

**Comment by radical** [comment] 2022-07-18 18:13
You can use the instructions from https://github.com/dotnet/linker/issues/2893#issue-1304160427 .
