### ISSUE TITLE
Fatal error in IL Linker

### ISSUE THREAD

**Issue by innermark** [dotnet/linker#2564] opened 2022-01-31 05:15 UTC
Fatal error in IL Linker
Unhandled exception. Mono.Linker.InternalErrorException: Step 'OutputStep' failed when processing assembly 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
 ---> Mono.Linker.LinkerFatalErrorException: ILLink: error IL1011: Failed to write 'obj\Release\net6.0\linked\netstandard.dll
 ---> System.UnauthorizedAccessException: Access to the path 'C:\projects\mcore\Mcore.Client\obj\Release\net6.0\linked\netstandard.dll' is denied.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Mono.Cecil.ModuleDefinition.GetFileStream(String fileName, FileMode mode, FileAccess access, FileShare share)
   at Mono.Cecil.ModuleDefinition.Write(String fileName, WriterParameters parameters)
   at Mono.Cecil.AssemblyDefinition.Write(String fileName, WriterParameters parameters)
   at Mono.Linker.Steps.OutputStep.WriteAssembly(AssemblyDefinition assembly, String directory, WriterParameters writerParameters)
   --- End of inner exception stack trace ---
   at Mono.Linker.Steps.OutputStep.WriteAssembly(AssemblyDefinition assembly, String directory, WriterParameters writerParameters)
   at Mono.Linker.Steps.OutputStep.OutputAssembly(AssemblyDefinition assembly)
   at Mono.Linker.Steps.BaseStep.Process(LinkContext context)
   --- End of inner exception stack trace ---
   at Mono.Linker.Steps.BaseStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at Mono.Linker.Driver.Run(ILogger customLogger)
   at Mono.Linker.Driver.Main(String[] args)

Just starting getting this error when trying to publish .net 6 blazor wasm client from VS 2022, was previously working

**Comment by vitek-karas** [comment] 2022-01-31 10:58
This looks like something else is holding onto the file in question. Can you try closing VS and deleting the `obj` and `bin` directories of the project (`Mcore.Client` in this case). And then try again?

**Comment by ordazl** [comment] 2022-01-31 15:20
I am running into a similar issue on my build server. I deleted the project folder and restarted the server to make sure no other process had a lock on the file and this is the following error I get, with subsequent builds getting the ILLink error IL1011 error:

The "GetFileHash" task failed unexpectedly.
System.AggregateException: One or more errors occurred. (Access to the path 'C:\BuildAgent\work\d0db4e4228df1be3\project-apps\Project.Apps\obj\Release\net6.0\linked\System.Private.CoreLib.dll' is denied.)
 ---> System.UnauthorizedAccessException: Access to the path 'C:\BuildAgent\work\d0db4e4228df1be3\project-apps\Project.Apps\obj\Release\net6.0\linked\System.Private.CoreLib.dll' is denied.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.File.OpenRead(String path)
   at Microsoft.Build.Tasks.GetFileHash.ComputeHash(Func'1 algorithmFactory, String filePath)
   at Microsoft.Build.Tasks.GetFileHash.<>c__DisplayClass28_0.<Execute>b__0(Int32 index)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0'1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0'1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction'1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action'1 body, Action'2 bodyWithState, Func'4 bodyWithLocal, Func'1 localInit, Action'1 localFinally)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action'1 body, Action'2 bodyWithState, Func'4 bodyWithLocal, Func'1 localInit, Action'1 localFinally)
   at System.Threading.Tasks.Parallel.For(Int32 fromInclusive, Int32 toExclusive, Action'1 body)
   at Microsoft.Build.Tasks.GetFileHash.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask

The build steps at the current moment are just checking out the project and immediately publishing, no other intermediate steps.

Also for .Net 6 Blazor WASM and VS 2022, this issue appeared to have started happening on Jan 30th.

**Comment by innermark** [comment] 2022-01-31 15:33
I did already try deleting bin and obj and rebooting machine. I have also seen the System.Private.CoreLib.dll in the error as the denied file. when looking in the linked folder however, I do not see either CoreLib.dll or netstandard.dll even being in that folder.

**Comment by vitek-karas** [comment] 2022-01-31 15:48
Since the issue started to happen so recently:
* Did you install new version of .NET 6 SDK around that time?
* Did the machine install some other update around that time?

It could be antivirus - we've seen cases where it blocks access to files at times, but typically it's not 100% repro.

**Comment by innermark** [comment] 2022-01-31 16:17
no updates or changes that I know of, it was working fine friday night, I made a few insignificant code changes in my project and tried to publish again yesterday and started getting the error

**Comment by vitek-karas** [comment] 2022-01-31 16:19
On the antivirus idea - do you know if the path where this happens is excluded from anti virus scanning or not?

**Comment by innermark** [comment] 2022-01-31 16:22
ah, looks like that is it, was just looking for AV logs and found this

<img width="496" alt="image" src="https://user-images.githubusercontent.com/12650034/151831863-f479b7af-87ea-435a-8bd5-0d02b497bbf9.png">

**Comment by vitek-karas** [comment] 2022-01-31 16:28
Hmm - unfortunately I have no idea why those files are detected as dangerous.

**Comment by innermark** [comment] 2022-01-31 16:43
not sure if this is helpful, but this is what bitdefender log shows

<img width="516" alt="image" src="https://user-images.githubusercontent.com/12650034/151835625-e4780e9a-f718-4684-9f98-102951014c6e.png">

**Comment by ordazl** [comment] 2022-01-31 16:58
I can confirm on my end it was our antivirus (Bit Defender), we configured it to ignore the build directory and have been able to build successfully on them after a reboot.

Thank you for the help.

**Comment by vitek-karas** [comment] 2022-01-31 17:04
@innermark this is super weird. The file `Link.semaphore` has size 0 bytes, always - we use it to synchronize the build via file system. There's no way it has a virus in it. My suggestion would be to report this to the antivirus developer as false positive.

**Closed** 2022-02-02 23:07 UTC
Labels: area-Linker: Steps
